name: Memote history

on: push

jobs:
  memote-history:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install memote
      run: pip install -r requirements/ci-requirements.txt
        
    - name: Setup variables
      id: setup
      run: |
        echo "::set-output name=history::history_report.html"
        echo "::set-output name=deployment::$(awk -F '=' '{if (! ($0 ~ /^;/) && $0 ~ /deployment/) print $2}' memote.ini | tr -d ' ')"
        echo "::set-output name=location::$(awk -F '=' '{if (! ($0 ~ /^;/) && $0 ~ /location/) print $2}' memote.ini | tr -d ' ')"
        echo "::set-output name=other-repo::gh-pages-repo"

    - name: Checkout repo for gh-pages branch
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ steps.setup.outputs.deployment }}
        path: ${{ steps.setup.outputs.other-repo }}

    - name: Convert model
      run: |
        touch .env
        python -c \
          'import ComplementaryScripts.io as io; \
          model = io.read_yeast_model(make_bigg_compliant=True); \
          io.write_yeast_model(model)'

    - name: Memote on push
      run: |
        memote run --skip-unchanged --solver-timeout 30
        # Generate the history report on the deployment branch
        memote report history --filename="${{ steps.setup.outputs.other-repo }}/${{ steps.setup.outputs.history }}" --solver-timeout 30

    - name: Auto-commit results
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_user_name: memote-bot
        commit_message: update memote history report
        file_pattern: ${{ steps.setup.outputs.history }}
        branch: ${{ steps.setup.outputs.deployment }}
        repository: ${{ steps.setup.outputs.other-repo }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
